import fs from "fs/promises";
import path from "path";
import { execSync } from "child_process";

const WORKSPACES_DIR = path.join(process.cwd(), "workspaces");

/**
 * Workspace manager for handling project directories
 */
export class WorkspaceManager {
  /**
   * Get the workspace directory for a project
   */
  static getProjectPath(projectId: number): string {
    return path.join(WORKSPACES_DIR, `project-${projectId}`);
  }

  /**
   * Initialize workspace directory for a project
   */
  static async initializeWorkspace(projectId: number): Promise<string> {
    const projectPath = this.getProjectPath(projectId);
    
    try {
      await fs.mkdir(projectPath, { recursive: true });
      
      // Create a basic README.md
      const readmePath = path.join(projectPath, "README.md");
      await fs.writeFile(
        readmePath,
        `# Project ${projectId}\n\nGenerated by Stackbird AI\n`
      );
      
      // Initialize git repository if not already initialized
      await this.initializeGit(projectPath);
      
      return projectPath;
    } catch (error) {
      console.error(`Failed to initialize workspace for project ${projectId}:`, error);
      throw error;
    }
  }

  /**
   * Initialize git repository in workspace
   */
  static async initializeGit(projectPath: string): Promise<void> {
    try {
      // Check if .git already exists
      const gitPath = path.join(projectPath, ".git");
      try {
        await fs.access(gitPath);
        console.log(`[Workspace] Git already initialized in ${projectPath}`);
        return; // Already initialized
      } catch {
        // .git doesn't exist, proceed with initialization
      }

      // Initialize git repository
      execSync("git init", { cwd: projectPath, stdio: "pipe" });
      console.log(`[Workspace] Initialized git repository in ${projectPath}`);
      
      // Configure git user for this repo (required for commits)
      execSync('git config user.email "ai@stackbird.dev"', { cwd: projectPath, stdio: "pipe" });
      execSync('git config user.name "Stackbird AI"', { cwd: projectPath, stdio: "pipe" });
      
      // Create .gitignore
      const gitignorePath = path.join(projectPath, ".gitignore");
      await fs.writeFile(
        gitignorePath,
        `# Dependencies\nnode_modules/\n__pycache__/\n*.pyc\n\n# Environment\n.env\n.env.local\n\n# IDE\n.vscode/\n.idea/\n*.swp\n*.swo\n\n# Aider\n.aider*\n\n# OS\n.DS_Store\nThumbs.db\n`
      );
      
      // Make initial commit
      execSync("git add .", { cwd: projectPath, stdio: "pipe" });
      execSync('git commit -m "Initial commit"', { cwd: projectPath, stdio: "pipe" });
      console.log(`[Workspace] Created initial git commit in ${projectPath}`);
    } catch (error) {
      console.error(`[Workspace] Failed to initialize git in ${projectPath}:`, error);
      // Don't throw - git initialization is not critical for workspace creation
    }
  }

  /**
   * Check if workspace exists
   */
  static async workspaceExists(projectId: number): Promise<boolean> {
    const projectPath = this.getProjectPath(projectId);
    try {
      await fs.access(projectPath);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Write file to workspace
   */
  static async writeFile(
    projectId: number,
    filePath: string,
    content: string
  ): Promise<void> {
    const projectPath = this.getProjectPath(projectId);
    const fullPath = path.join(projectPath, filePath);
    
    // Ensure directory exists
    await fs.mkdir(path.dirname(fullPath), { recursive: true });
    
    await fs.writeFile(fullPath, content, "utf-8");
  }

  /**
   * Read file from workspace
   */
  static async readFile(projectId: number, filePath: string): Promise<string> {
    const projectPath = this.getProjectPath(projectId);
    const fullPath = path.join(projectPath, filePath);
    
    return await fs.readFile(fullPath, "utf-8");
  }

  /**
   * List files in workspace
   * Excludes hidden files (.git, .aider*, etc.) and system files
   */
  static async listFiles(projectId: number, dirPath: string = ""): Promise<string[]> {
    const projectPath = this.getProjectPath(projectId);
    const fullPath = path.join(projectPath, dirPath);
    
    try {
      const entries = await fs.readdir(fullPath, { withFileTypes: true });
      const files: string[] = [];
      
      for (const entry of entries) {
        // Skip hidden files and Aider cache
        if (entry.name.startsWith('.')) {
          continue;
        }
        
        const relativePath = path.join(dirPath, entry.name);
        if (entry.isDirectory()) {
          const subFiles = await this.listFiles(projectId, relativePath);
          files.push(...subFiles);
        } else {
          files.push(relativePath);
        }
      }
      
      return files;
    } catch (error) {
      console.error(`Failed to list files in ${fullPath}:`, error);
      return [];
    }
  }

  /**
   * Delete workspace
   */
  static async deleteWorkspace(projectId: number): Promise<void> {
    const projectPath = this.getProjectPath(projectId);
    
    try {
      await fs.rm(projectPath, { recursive: true, force: true });
    } catch (error) {
      console.error(`Failed to delete workspace for project ${projectId}:`, error);
    }
  }
}

// Ensure workspaces directory exists on startup
(async () => {
  try {
    await fs.mkdir(WORKSPACES_DIR, { recursive: true });
  } catch (error) {
    console.error("Failed to create workspaces directory:", error);
  }
})();
