import fs from "fs/promises";
import path from "path";

const WORKSPACES_DIR = path.join(process.cwd(), "workspaces");

/**
 * Workspace manager for handling project directories
 */
export class WorkspaceManager {
  /**
   * Get the workspace directory for a project
   */
  static getProjectPath(projectId: number): string {
    return path.join(WORKSPACES_DIR, `project-${projectId}`);
  }

  /**
   * Initialize workspace directory for a project
   */
  static async initializeWorkspace(projectId: number): Promise<string> {
    const projectPath = this.getProjectPath(projectId);
    
    try {
      await fs.mkdir(projectPath, { recursive: true });
      
      // Create a basic README.md
      const readmePath = path.join(projectPath, "README.md");
      await fs.writeFile(
        readmePath,
        `# Project ${projectId}\n\nGenerated by Stackbird AI\n`
      );
      
      return projectPath;
    } catch (error) {
      console.error(`Failed to initialize workspace for project ${projectId}:`, error);
      throw error;
    }
  }

  /**
   * Check if workspace exists
   */
  static async workspaceExists(projectId: number): Promise<boolean> {
    const projectPath = this.getProjectPath(projectId);
    try {
      await fs.access(projectPath);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Write file to workspace
   */
  static async writeFile(
    projectId: number,
    filePath: string,
    content: string
  ): Promise<void> {
    const projectPath = this.getProjectPath(projectId);
    const fullPath = path.join(projectPath, filePath);
    
    // Ensure directory exists
    await fs.mkdir(path.dirname(fullPath), { recursive: true });
    
    await fs.writeFile(fullPath, content, "utf-8");
  }

  /**
   * Read file from workspace
   */
  static async readFile(projectId: number, filePath: string): Promise<string> {
    const projectPath = this.getProjectPath(projectId);
    const fullPath = path.join(projectPath, filePath);
    
    return await fs.readFile(fullPath, "utf-8");
  }

  /**
   * List files in workspace
   */
  static async listFiles(projectId: number, dirPath: string = ""): Promise<string[]> {
    const projectPath = this.getProjectPath(projectId);
    const fullPath = path.join(projectPath, dirPath);
    
    try {
      const entries = await fs.readdir(fullPath, { withFileTypes: true });
      const files: string[] = [];
      
      for (const entry of entries) {
        const relativePath = path.join(dirPath, entry.name);
        if (entry.isDirectory()) {
          const subFiles = await this.listFiles(projectId, relativePath);
          files.push(...subFiles);
        } else {
          files.push(relativePath);
        }
      }
      
      return files;
    } catch (error) {
      console.error(`Failed to list files in ${fullPath}:`, error);
      return [];
    }
  }

  /**
   * Delete workspace
   */
  static async deleteWorkspace(projectId: number): Promise<void> {
    const projectPath = this.getProjectPath(projectId);
    
    try {
      await fs.rm(projectPath, { recursive: true, force: true });
    } catch (error) {
      console.error(`Failed to delete workspace for project ${projectId}:`, error);
    }
  }
}

// Ensure workspaces directory exists on startup
(async () => {
  try {
    await fs.mkdir(WORKSPACES_DIR, { recursive: true });
  } catch (error) {
    console.error("Failed to create workspaces directory:", error);
  }
})();
